spring:
  datasource:
    url: jdbc:mysql://localhost/test7?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
    username: root
    password: qingdao
#    url: jdbc:mysql://localhost/test2?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
#    username: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update

server:
  port: 1023

sui:
  contract:
    jsonrpc:
      #url: "http://localhost:9000"
      #url: "https://fullnode.devnet.sui.io/"
      url: "https://fullnode.testnet.sui.io/"
    package-publish-transactions:
      common: "DzbCrgkwdrdADnauKLFFAJsAHnRyX2i2CBmAnBm1A98"
      default: "FtXxnFjM9apbj5nLHHxTWzMPz4vM7wXBfM7gUQSTvV31"
#    pull-day-summary-events:
#      day-summary-created:
#        fixed-delay: 6000
#    pull-order-v2-events:
#      order-v2-created:
#        fixed-delay: 6000
